#!/bin/sh
set -eu

printf 'pacman-conf %s\n' "$*" >> "$MOGUET_TEST_COMMAND_LOG"

if [ "$#" -eq 1 ] && [ "$1" = HoldPkg ]; then
    if [ -n "${MOGUET_TEST_HOLDPKG:-}" ]; then
        printf '%s\n' "$MOGUET_TEST_HOLDPKG"
    fi
    exit "${MOGUET_TEST_HOLDPKG_EXIT_CODE:-0}"
fi

if [ "$#" -eq 1 ] && [ "${1:-}" = "--repo-list" ]; then
    exit_code=${MOGUET_TEST_PACMAN_CONF_REPOSITORY_LIST_EXIT_CODE:-0}
    if [ "$exit_code" -ne 0 ]; then
        exit "$exit_code"
    fi
    if [ -n "${MOGUET_TEST_PACMAN_CONF_REPOSITORY_LIST:-}" ]; then
        printf '%s\n' "$MOGUET_TEST_PACMAN_CONF_REPOSITORY_LIST"
    fi
    exit 0
fi

if [ "$#" -ne 3 ] ||
   [ "${1:-}" != "--verbose" ] ||
   [ "${2:-}" != "RootDir" ] ||
   [ "${3:-}" != "DBPath" ]; then
    exit 2
fi

exit_code=${MOGUET_TEST_PACKAGE_METADATA_PACMAN_CONF_EXIT_CODE:-0}
failure_at=${MOGUET_TEST_PACKAGE_METADATA_PACMAN_CONF_FAILURE_AT:-}
case $failure_at in
    '')
        should_fail=1
        ;;
    *[!0-9]*)
        exit 2
        ;;
    *)
        call_count=$(/usr/bin/grep -Fxc -- \
            'pacman-conf --verbose RootDir DBPath' "$MOGUET_TEST_COMMAND_LOG")
        if [ "$call_count" -eq "$failure_at" ]; then
            should_fail=1
        else
            should_fail=0
        fi
        ;;
esac
if [ "$should_fail" -eq 1 ] && [ "$exit_code" -ne 0 ]; then
    exit "$exit_code"
fi

printf 'RootDir = %s\nDBPath = %s\n' \
    "${MOGUET_TEST_PACKAGE_METADATA_ROOT_DIR:-/}" \
    "${MOGUET_TEST_PACKAGE_METADATA_DB_PATH:-/var/lib/pacman}"
