#!/bin/sh
printf 'vercmp %s\n' "$*" >> "$MOGUET_TEST_COMMAND_LOG"
argument_index=0
if [ -n "${MOGUET_TEST_VERCMP_ARGV_LOG:-}" ]; then
    printf 'argv-begin\n' >> "$MOGUET_TEST_VERCMP_ARGV_LOG"
fi
for vercmp_arg in "$@"; do
    if [ -n "${MOGUET_TEST_VERCMP_ARGV_LOG:-}" ]; then
        printf 'arg[%s]=<%s>\n' "$argument_index" "$vercmp_arg" >> "$MOGUET_TEST_VERCMP_ARGV_LOG"
    fi
    argument_index=$((argument_index + 1))
done
if [ -n "${MOGUET_TEST_VERCMP_ARGV_LOG:-}" ]; then
    printf 'argv-end\n' >> "$MOGUET_TEST_VERCMP_ARGV_LOG"
fi
if [ "${MOGUET_TEST_VERCMP_OUTPUT+x}" = x ]; then
    printf '%s\n' "$MOGUET_TEST_VERCMP_OUTPUT"
    exit "${MOGUET_TEST_VERCMP_EXIT_CODE:-0}"
fi
exec /usr/bin/vercmp "$@"
