# Generated by scripts/generate_completions.py; do not edit.
# Description locale: en
# Upstream -Q spelling: pacman 7.1.0; raw help SHA256 b59c241b782288efd34e84cf514e85f2106547f81acfc6fd28adffb9989a3267
# Pinned generation input; no runtime upstream discovery.
# Canonical closed grammar (projected from source/cli_authority.hpp):
#   build [--use-preference] <pkg> [V=K...]
#   build --local [--use-patches] <directory> [V=K...]
#   upgrade
#   upgrade-aur
#   upgrade-all
#   clean
#   deps [--recursive] <pkg>...
#   plan <pkg>...
#   fetch <pkg>...
#   add-src <item>...
#   edit-src <pkg>...
#   list-src
#   del-src <pkg>...
#   revert <pkg>...
#   add-patch <directory> <patch-directory> <patch-file>...
#   update-patch <directory> <patch-directory> <patch-file>...
#   del-patch <directory> <package-base>
#   list-patch
#   -G <pkg> [--output-dir=DIR]
#   -Gp <pkg>
#   -S --select [--needed] <query>
#   -Syu [--needed]
#   -Syu --repo [--needed]
#   -Su [--needed]
#   -Su --repo [--needed]

_moguet_option_id() {
    case "$1" in
        -h|--help) printf '%s' 13 ;;
        -V|--version) printf '%s' 14 ;;
        --edit) printf '%s' 0 ;;
        --noedit) printf '%s' 1 ;;
        --diff) printf '%s' 2 ;;
        --nodiff) printf '%s' 3 ;;
        --noconfirm) printf '%s' 4 ;;
        --dry-run) printf '%s' 5 ;;
        --build-mode|--build-mode=*) printf '%s' 6 ;;
        --rebuild) printf '%s' 7 ;;
        --cleanbuild) printf '%s' 8 ;;
        --rmdeps) printf '%s' 9 ;;
        --select) printf '%s' 10 ;;
        --aur) printf '%s' 11 ;;
        --repo) printf '%s' 12 ;;
        --details) printf '%s' 20 ;;
        --local) printf '%s' 15 ;;
        --use-preference) printf '%s' 21 ;;
        --use-patches) printf '%s' 22 ;;
        --output-dir|--output-dir=*) printf '%s' 16 ;;
        --recursive) printf '%s' 17 ;;
        --needed) printf '%s' 18 ;;
        *) return 1 ;;
    esac
}

_moguet_has_option_id() {
    local expected="$1" word actual
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        actual="$(_moguet_option_id "$word" || true)"
        [[ $actual == "$expected" ]] && return 0
    done
    return 1
}

_moguet_find_operation() {
    local word
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        case "$word" in
        -h|--help|-V|--version|build|upgrade|upgrade-aur|upgrade-all|clean|deps|plan|fetch|add-src|edit-src|list-src|del-src|revert|add-patch|update-patch|del-patch|list-patch|-G|-Gp|-S|-Syu|-Su|-Ss|-Si|-Qua|-Q) printf '%s' "$word"; return 0 ;;
        esac
        _moguet_option_id "$word" >/dev/null && continue
        if [[ $word == -* ]]; then
            printf '%s' __delegated__
            return 0
        fi
        printf '%s' __invalid__
        return 0
    done
    return 1
}

_moguet_has_operand() {
    local expected_operation="$1" word actual seen_operation=false
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        if [[ $seen_operation == false ]]; then
            if [[ $word == "$expected_operation" ]]; then
                seen_operation=true
            fi
            continue
        fi
        actual="$(_moguet_option_id "$word" || true)"
        [[ -z $actual ]] && return 0
    done
    return 1
}

_moguet_is_assignment_operand() {
    [[ $1 == *=* ]]
}

_moguet_form_prefix_valid() {
    local expected_operation="$1" form_index="$2" word actual
    local seen_operation=false
    local -a operands=()
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        if [[ $seen_operation == false ]]; then
            [[ $word == "$expected_operation" ]] && seen_operation=true
            continue
        fi
        actual="$(_moguet_option_id "$word" || true)"
        [[ -n $actual ]] && continue
        operands+=("$word")
    done
    case "$expected_operation:$form_index" in
        build:0)
            (( ${#operands[@]} == 0 )) && return 0
            _moguet_is_assignment_operand "${operands[0]}" && return 1
            for word in "${operands[@]:1}"; do
                _moguet_is_assignment_operand "$word" || return 1
            done
            return 0
            ;;
        build:1)
            (( ${#operands[@]} == 0 )) && return 0
            _moguet_is_assignment_operand "${operands[0]}" && return 1
            for word in "${operands[@]:1}"; do
                _moguet_is_assignment_operand "$word" || return 1
            done
            return 0
            ;;
        upgrade:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        upgrade-aur:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        upgrade-all:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        clean:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        deps:0)
            return 0
            ;;
        plan:0)
            return 0
            ;;
        fetch:0)
            return 0
            ;;
        add-src:0)
            (( ${#operands[@]} == 0 )) && return 0
            _moguet_is_assignment_operand "${operands[0]}" && return 1
            return 0
            ;;
        edit-src:0)
            return 0
            ;;
        list-src:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        del-src:0)
            return 0
            ;;
        revert:0)
            return 0
            ;;
        add-patch:0)
            return 0
            ;;
        update-patch:0)
            return 0
            ;;
        del-patch:0)
            (( ${#operands[@]} <= 2 )) && return 0
            return 1
            ;;
        list-patch:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        -G:0)
            (( ${#operands[@]} <= 1 )) && return 0
            return 1
            ;;
        -Gp:0)
            (( ${#operands[@]} <= 1 )) && return 0
            return 1
            ;;
        -S:0)
            (( ${#operands[@]} <= 1 )) && return 0
            return 1
            ;;
        -Syu:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        -Syu:1)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        -Su:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        -Su:1)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        *) return 1 ;;
    esac
}

_moguet_conflicts_with_present_option() {
    case "$1" in
        0) _moguet_has_option_id 1 || _moguet_has_option_id 22 ;;
        1) _moguet_has_option_id 0 ;;
        2) _moguet_has_option_id 3 ;;
        3) _moguet_has_option_id 2 ;;
        5) _moguet_has_option_id 22 ;;
        6) _moguet_has_option_id 7 || _moguet_has_option_id 8 ;;
        7) _moguet_has_option_id 6 || _moguet_has_option_id 8 ;;
        8) _moguet_has_option_id 6 || _moguet_has_option_id 7 ;;
        9) _moguet_has_option_id 10 ;;
        10) _moguet_has_option_id 9 ;;
        11) _moguet_has_option_id 12 ;;
        12) _moguet_has_option_id 11 ;;
        21) _moguet_has_option_id 22 ;;
        22) _moguet_has_option_id 0 || _moguet_has_option_id 5 || _moguet_has_option_id 21 ;;
        *) return 1 ;;
    esac
}


_moguet_current_word() {
    local word="${COMP_WORDS[COMP_CWORD]}" joined start
    local LC_ALL=C
    current_word_start=$COMP_CWORD
    if [[ -n ${COMP_LINE-} ]]; then
        while (( current_word_start > 1 )); do
            joined=${COMP_WORDS[current_word_start-1]}$word
            start=$((COMP_POINT-${#joined}))
            (( start >= 0 )) || break
            [[ ${COMP_LINE:start:${#joined}} == "$joined" ]] || break
            word=$joined
            ((--current_word_start))
        done
    fi
    _moguet_unquote_prefix "$word"
}

_moguet_value_family() {
    REPLY=
    case "$1" in
        --build-mode|--build-mode=*)
            REPLY=${1#--build-mode=}
            [[ $1 == --build-mode ]] && REPLY=
            return 0 ;;
        --rebuild) REPLY=rebuild; return 0 ;;
        --cleanbuild) REPLY=clean; return 0 ;;
    esac
    return 1
}

_moguet_logical_words() {
    # COMP_WORDS also splits completed attached values. Reassemble the native
    # fragments only where COMP_LINE proves adjacency, then decode shell quotes
    # once. This is lexical plumbing, not an operation/value grammar parser.
    local index position=0 word spaced logical_cword=$COMP_CWORD
    local LC_ALL=C
    local -a logical_words=()
    if [[ -n ${COMP_LINE-} ]]; then
        for ((index=0; index<${#COMP_WORDS[@]}; ++index)); do
            word=${COMP_WORDS[index]}
            spaced=false
            while [[ ${COMP_LINE:position:1} == [$' \t\n'] ]]; do
                spaced=true
                ((++position))
            done
            [[ ${COMP_LINE:position:${#word}} == "$word" ]] || return 1
            if [[ $spaced == true || ${#logical_words[@]} == 0 ]]; then
                logical_words+=("$word")
            else
                logical_words[${#logical_words[@]}-1]+=$word
            fi
            (( index == COMP_CWORD )) && logical_cword=$((${#logical_words[@]}-1))
            ((position+=${#word}))
        done
    else
        logical_words=("${COMP_WORDS[@]}")
    fi
    for ((index=0; index<${#logical_words[@]}; ++index)); do
        _moguet_unquote_prefix "${logical_words[index]}"
        logical_words[index]=$REPLY
    done
    COMP_WORDS=("${logical_words[@]}")
    COMP_CWORD=$logical_cword
    return 0
}

_moguet_typed_values() {
    local option_prefix word requested fixed= pending=false value
    local -a values
    case "$cur" in
        --build-mode=*)
            option_prefix=--build-mode=
            values=(normal rebuild clean)
            ;;
        *) return 1 ;;
    esac
    # Recognized attached values own this event, including suppressed/no-match
    # contexts. They never fall through to the package provider.
    COMPREPLY=()
    [[ ${#COMP_WORDS[@]} == $((COMP_CWORD+1)) ]] || return 0
    [[ " ${candidates[*]} " == *" $option_prefix "* ]] || return 0
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        if [[ $pending == true ]]; then pending=false; continue; fi
        case "$word" in
        --) return 0 ;;
        --arch|--assume-installed|--cachedir|--color|--config|--dbpath|--gpgdir|--hookdir|--ignore|--ignoregroup|--logfile|--overwrite|--print-format|--root|--sysroot|-b|-r) pending=true; continue ;;
        esac
        if _moguet_value_family "$word"; then
            requested=$REPLY
            [[ " ${values[*]} " == *" $requested "* && -n $requested ]] || return 0
            [[ -z $fixed || $fixed == "$requested" ]] || return 0
            fixed=$requested
        fi
    done
    [[ $pending == false ]] || return 0
    local prefix=${cur#"$option_prefix"}
    for value in "${values[@]}"; do
        [[ -z $fixed || $fixed == "$value" ]] || continue
        [[ $value == "$prefix"* ]] || continue
        COMPREPLY+=("$typed_insert_prefix$value")
    done
    return 0
}

_moguet_query_context() {
    local seen=false pending=false word index
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        if [[ $pending == true ]]; then pending=false; continue; fi
        case "$word" in
        --) return 1 ;;
        -Q) [[ $seen == false ]] || return 1; seen=true ;;
        --noconfirm|--needed) continue ;;
        --arch|--assume-installed|--cachedir|--color|--config|--dbpath|--gpgdir|--hookdir|--ignore|--ignoregroup|--logfile|--overwrite|--print-format|--root|--sysroot|-b|-r) [[ $seen == true ]] || return 1; pending=true ;;
        --arch=*|--assume-installed=*|--cachedir=*|--color=*|--config=*|--dbpath=*|--gpgdir=*|--hookdir=*|--ignore=*|--ignoregroup=*|--logfile=*|--overwrite=*|--print-format=*|--root=*|--sysroot=*) [[ $seen == true ]] || return 1 ;;
        *) return 1 ;;
        esac
    done
    [[ $seen == true && $pending == false ]]
}


_moguet() {
    local cur operation candidate option_id REPLY strip_prefix typed_insert_prefix
    local words_are_logical=false
    local current_word_start original_cword=$COMP_CWORD
    local -a COMP_WORDS=("${COMP_WORDS[@]}")
    local COMP_CWORD=$COMP_CWORD
    local -a candidates filtered
    cur="${COMP_WORDS[COMP_CWORD]}"
    _moguet_current_word
    case "$REPLY" in
    --build-mode=*)
        cur=$REPLY
        if (( current_word_start == original_cword )); then
            typed_insert_prefix=${cur%%=*}=
        else
            typed_insert_prefix=
        fi
        _moguet_logical_words || { COMPREPLY=(); return 0; }
        words_are_logical=true
        cur=${COMP_WORDS[COMP_CWORD]}
        ;;
    esac
    operation="$(_moguet_find_operation || true)"

    if [[ -z $operation ]]; then
        candidates=(build upgrade upgrade-aur upgrade-all clean deps plan fetch add-src edit-src list-src del-src revert add-patch update-patch del-patch list-patch -G -Gp -S -Syu -Su -Ss -Si -Qua -h --help -V --version --edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --rmdeps --select --aur --repo --details)
    else
        case "$operation" in
        build)
            if _moguet_has_option_id 15; then
                if _moguet_form_prefix_valid build 1; then
                    candidates=(--edit --noedit --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --local --use-patches)
                else
                    candidates=()
                fi
            elif _moguet_has_operand build; then
                if _moguet_form_prefix_valid build 0; then
                    candidates=(--use-preference --edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --details)
                else
                    candidates=()
                fi
            else
                candidates=(--use-preference --edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --details --local)
            fi
            ;;
        upgrade)
            if _moguet_form_prefix_valid upgrade 0; then
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild)
            else
                candidates=()
            fi
            ;;
        upgrade-aur)
            if _moguet_form_prefix_valid upgrade-aur 0; then
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --details)
            else
                candidates=()
            fi
            ;;
        upgrade-all)
            if _moguet_form_prefix_valid upgrade-all 0; then
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --details)
            else
                candidates=()
            fi
            ;;
        clean)
            if _moguet_form_prefix_valid clean 0; then
                candidates=(--noconfirm)
            else
                candidates=()
            fi
            ;;
        deps)
            if _moguet_form_prefix_valid deps 0; then
                candidates=(--noconfirm --details --recursive)
            else
                candidates=()
            fi
            ;;
        plan)
            if _moguet_form_prefix_valid plan 0; then
                candidates=(--noconfirm --details)
            else
                candidates=()
            fi
            ;;
        fetch)
            if _moguet_form_prefix_valid fetch 0; then
                candidates=(--noconfirm --dry-run)
            else
                candidates=()
            fi
            ;;
        add-src)
            if _moguet_form_prefix_valid add-src 0; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        edit-src)
            if _moguet_form_prefix_valid edit-src 0; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        list-src)
            if _moguet_form_prefix_valid list-src 0; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        del-src)
            if _moguet_form_prefix_valid del-src 0; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        revert)
            if _moguet_form_prefix_valid revert 0; then
                candidates=(--noconfirm)
            else
                candidates=()
            fi
            ;;
        add-patch)
            if _moguet_form_prefix_valid add-patch 0; then
                candidates=(--noconfirm)
            else
                candidates=()
            fi
            ;;
        update-patch)
            if _moguet_form_prefix_valid update-patch 0; then
                candidates=(--noconfirm)
            else
                candidates=()
            fi
            ;;
        del-patch)
            if _moguet_form_prefix_valid del-patch 0; then
                candidates=(--noconfirm)
            else
                candidates=()
            fi
            ;;
        list-patch)
            if _moguet_form_prefix_valid list-patch 0; then
                candidates=(--details)
            else
                candidates=()
            fi
            ;;
        -G)
            if _moguet_form_prefix_valid -G 0; then
                candidates=(--output-dir=)
            else
                candidates=()
            fi
            ;;
        -Gp)
            if _moguet_form_prefix_valid -Gp 0; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        -S)
            if _moguet_has_option_id 10; then
                if _moguet_form_prefix_valid -S 0; then
                    candidates=(--select --needed --edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --aur --repo --details)
                else
                    candidates=()
                fi
            else
                candidates=(--needed --noconfirm --select)
            fi
            ;;
        -Syu)
            if _moguet_has_option_id 12; then
                if _moguet_form_prefix_valid -Syu 1; then
                    candidates=(--repo --needed --noconfirm --dry-run --details)
                else
                    candidates=()
                fi
            elif _moguet_has_operand -Syu; then
                candidates=(--needed --noconfirm)
            else
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --details --build-mode= --rebuild --cleanbuild --needed --repo)
            fi
            ;;
        -Su)
            if _moguet_has_option_id 12; then
                if _moguet_form_prefix_valid -Su 1; then
                    candidates=(--repo --needed --noconfirm --dry-run --details)
                else
                    candidates=()
                fi
            elif _moguet_has_operand -Su; then
                candidates=(--needed --noconfirm)
            else
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --details --build-mode= --rebuild --cleanbuild --needed --repo)
            fi
            ;;
        -Ss) candidates=(--needed --noconfirm) ;;
        -Si) candidates=(--needed --noconfirm) ;;
        -Qua) candidates=(--needed --noconfirm) ;;
        -h) candidates=() ;;
        --help) candidates=() ;;
        -V) candidates=() ;;
        --version) candidates=() ;;
        -Q)
            if [[ $words_are_logical == true ]] || _moguet_logical_words; then
                words_are_logical=true
                cur=${COMP_WORDS[COMP_CWORD]}
                if _moguet_query_context; then
                    candidates=(--arch --cachedir --changelog --check --color --config --confirm --dbpath --debug --deps --disable-download-timeout --disable-sandbox --disable-sandbox-filesystem --disable-sandbox-syscalls --explicit --file --foreign --gpgdir --groups --hookdir --info --list --logfile --native --needed --noconfirm --owns --quiet --root --search --sysroot --unrequired --upgrades --verbose -b -c -d -e -g -i -k -l -m -n -o -p -q -r -s -t -u -v)
                else
                    candidates=()
                fi
            else
                candidates=()
            fi
            ;;
        __delegated__) candidates=(--needed --noconfirm) ;;
        *) candidates=() ;;
        esac
    fi

    if [[ $operation == -Qua ]] && [[ " ${candidates[*]} " != *' --details '* ]]; then candidates+=(--details); fi
    if [[ $operation == -S ]] && _moguet_has_option_id 5 && [[ " ${candidates[*]} " != *' --details '* ]]; then candidates+=(--details); fi

    _moguet_typed_values && return 0

    filtered=()
    for candidate in "${candidates[@]}"; do
        option_id="$(_moguet_option_id "$candidate" || true)"
        if [[ -n $option_id ]]; then
            case "$option_id" in
            13|14|15|21|22|16)
                _moguet_has_option_id "$option_id" && continue
                ;;
            esac
            _moguet_conflicts_with_present_option "$option_id" && continue
        fi
        filtered+=("$candidate")
    done

    COMPREPLY=()
    while IFS= read -r candidate; do
        COMPREPLY+=("$candidate")
    done < <(compgen -W "${filtered[*]}" -- "$cur" || true)

    # One provider call, outside all static candidate scans.
    _moguet_repository_context && _moguet_repository_packages "$REPLY" "$strip_prefix"
    return 0
}

_moguet_repository_context() {
    local word before= index start
    local LC_ALL=C
    [[ $COMP_CWORD -ge 2 && ${#COMP_WORDS[@]} == $((COMP_CWORD+1)) ]] || return 1
    case "${COMP_WORDS[1]}" in
    -S) ;;
    *) return 1 ;;
    esac
    word=${COMP_WORDS[2]}
    for ((index=3; index<=COMP_CWORD; ++index)); do
        before=$word
        word+=${COMP_WORDS[index]}
    done
    if (( COMP_CWORD > 2 )); then
        # Bash splits valid package '@' at COMP_WORDBREAKS. Rejoin only
        # adjacent fragments of this raw current word, never separate argv.
        [[ -n ${COMP_LINE-} ]] || return 1
        start=$((COMP_POINT-${#word}))
        (( start > 0 )) || return 1
        [[ ${COMP_LINE:start:${#word}} == "$word" &&
           ${COMP_LINE:start-1:1} == [$' \t'] ]] || return 1
    fi
    _moguet_unquote_prefix "$before"
    # Readline replaces the preceding wordbreak character together with its
    # RHS (ch@to), even though COMP_WORDS exposes '@' as a separate entry.
    strip_prefix=${REPLY%@}
    _moguet_unquote_prefix "$word"
    [[ $REPLY != -* ]]
}

_moguet_unquote_prefix() {
    # COMP_WORDS retains shell quotes. Decode syntax only, never eval/expand
    # substitutions. An unfinished quote is normal in an incomplete word.
    local word="$1" quote= char next index
    REPLY=
    for ((index=0; index<${#word}; ++index)); do
        char=${word:index:1}
        if [[ $quote == "'" ]]; then
            if [[ $char == "'" ]]; then quote=; else REPLY+=$char; fi
        elif [[ $char == "$quote" && -n $quote ]]; then
            quote=
        elif [[ -z $quote && ( $char == "'" || $char == '"' ) ]]; then
            quote=$char
        elif [[ $char == $'\\' ]]; then
            next=${word:index+1:1}
            if [[ -n $next && ( -z $quote || $next == [\$\`\"\\] ) ]]; then
                REPLY+=$next
                ((++index))
            else
                REPLY+=$char
            fi
        else
            REPLY+=$char
        fi
    done
}

_moguet_repository_packages() {
    local prefix="$1" strip_prefix="$2" helper=@MOGUET_REPOSITORY_PREFIX_HELPER_BASH@ output candidate previous=
    local LC_ALL=C
    local -a packages=()
    [[ $helper == /* && -x $helper ]] || return 0
    # Preserve the final newline and exit status. read -d NUL detects binary
    # protocol corruption before Bash command substitution can drop NULs.
    output="$(set -o pipefail
        "$helper" "$prefix" 2>/dev/null | {
            IFS= read -r -d '' output && exit 1
            printf '%s\001' "$output"
        }
    )" || return 0
    output=${output%$'\001'}
    [[ ${#output} -le 65536 ]] || return 0
    [[ -z $output ]] && return 0
    [[ $output == *$'\n' ]] || return 0
    while IFS= read -r candidate; do
        [[ $candidate =~ ^[A-Za-z0-9@._+][A-Za-z0-9@._+-]*$ &&
           $candidate != . && $candidate != .. &&
           $candidate == "$prefix"* ]] || return 0
        [[ -z $previous || $candidate > $previous ]] || return 0
        packages+=("$candidate")
        [[ ${#packages[@]} -le 256 ]] || return 0
        previous=$candidate
    done <<< "${output%$'\n'}"
    for candidate in "${packages[@]}"; do
        COMPREPLY+=("${candidate#"$strip_prefix"}")
    done
    return 0
}

complete -F _moguet moguet
