# Generated by scripts/generate_completions.py; do not edit.
# Description locale: en
# Canonical closed grammar (projected from source/cli_authority.hpp):
#   build <pkg> [V=K...]
#   build --local <directory> [V=K...]
#   upgrade
#   upgrade-aur
#   upgrade-all
#   clean
#   deps [--recursive] <pkg>...
#   plan <pkg>...
#   fetch <pkg>...
#   add-src <item>...
#   edit-src <pkg>...
#   list-src
#   del-src <pkg>...
#   revert <pkg>...
#   -G <pkg> [--output-dir=DIR]
#   -Gp <pkg>
#   -S --select [--needed] <query>
#   -Syu [--needed]
#   -Syu --repo [--needed]
#   -Su [--needed]
#   -Su --repo [--needed]

_moguet_option_id() {
    case "$1" in
        -h|--help) printf '%s' 13 ;;
        -V|--version) printf '%s' 14 ;;
        --edit) printf '%s' 0 ;;
        --noedit) printf '%s' 1 ;;
        --diff) printf '%s' 2 ;;
        --nodiff) printf '%s' 3 ;;
        --noconfirm) printf '%s' 4 ;;
        --dry-run) printf '%s' 5 ;;
        --build-mode|--build-mode=*) printf '%s' 6 ;;
        --rebuild) printf '%s' 7 ;;
        --cleanbuild) printf '%s' 8 ;;
        --rmdeps) printf '%s' 9 ;;
        --select) printf '%s' 10 ;;
        --aur) printf '%s' 11 ;;
        --repo) printf '%s' 12 ;;
        --details) printf '%s' 20 ;;
        --local) printf '%s' 15 ;;
        --output-dir|--output-dir=*) printf '%s' 16 ;;
        --recursive) printf '%s' 17 ;;
        --needed) printf '%s' 18 ;;
        *) return 1 ;;
    esac
}

_moguet_has_option_id() {
    local expected="$1" word actual
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        actual="$(_moguet_option_id "$word" || true)"
        [[ $actual == "$expected" ]] && return 0
    done
    return 1
}

_moguet_find_operation() {
    local word
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        case "$word" in
        -h|--help|-V|--version|build|upgrade|upgrade-aur|upgrade-all|clean|deps|plan|fetch|add-src|edit-src|list-src|del-src|revert|-G|-Gp|-S|-Syu|-Su|-Ss|-Si|-Qua) printf '%s' "$word"; return 0 ;;
        esac
        _moguet_option_id "$word" >/dev/null && continue
        if [[ $word == -* ]]; then
            printf '%s' __delegated__
            return 0
        fi
        printf '%s' __invalid__
        return 0
    done
    return 1
}

_moguet_has_operand() {
    local expected_operation="$1" word actual seen_operation=false
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        if [[ $seen_operation == false ]]; then
            if [[ $word == "$expected_operation" ]]; then
                seen_operation=true
            fi
            continue
        fi
        actual="$(_moguet_option_id "$word" || true)"
        [[ -z $actual ]] && return 0
    done
    return 1
}

_moguet_is_assignment_operand() {
    [[ $1 == *=* ]]
}

_moguet_form_prefix_valid() {
    local expected_operation="$1" form_index="$2" word actual
    local seen_operation=false
    local -a operands=()
    for word in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        if [[ $seen_operation == false ]]; then
            [[ $word == "$expected_operation" ]] && seen_operation=true
            continue
        fi
        actual="$(_moguet_option_id "$word" || true)"
        [[ -n $actual ]] && continue
        operands+=("$word")
    done
    case "$expected_operation:$form_index" in
        build:0)
            (( ${#operands[@]} == 0 )) && return 0
            _moguet_is_assignment_operand "${operands[0]}" && return 1
            for word in "${operands[@]:1}"; do
                _moguet_is_assignment_operand "$word" || return 1
            done
            return 0
            ;;
        build:1)
            (( ${#operands[@]} == 0 )) && return 0
            _moguet_is_assignment_operand "${operands[0]}" && return 1
            for word in "${operands[@]:1}"; do
                _moguet_is_assignment_operand "$word" || return 1
            done
            return 0
            ;;
        upgrade:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        upgrade-aur:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        upgrade-all:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        clean:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        deps:0)
            return 0
            ;;
        plan:0)
            return 0
            ;;
        fetch:0)
            return 0
            ;;
        add-src:0)
            (( ${#operands[@]} == 0 )) && return 0
            _moguet_is_assignment_operand "${operands[0]}" && return 1
            return 0
            ;;
        edit-src:0)
            return 0
            ;;
        list-src:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        del-src:0)
            return 0
            ;;
        revert:0)
            return 0
            ;;
        -G:0)
            (( ${#operands[@]} <= 1 )) && return 0
            return 1
            ;;
        -Gp:0)
            (( ${#operands[@]} <= 1 )) && return 0
            return 1
            ;;
        -S:0)
            (( ${#operands[@]} <= 1 )) && return 0
            return 1
            ;;
        -Syu:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        -Syu:1)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        -Su:0)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        -Su:1)
            (( ${#operands[@]} <= 0 )) && return 0
            return 1
            ;;
        *) return 1 ;;
    esac
}

_moguet_conflicts_with_present_option() {
    case "$1" in
        0) _moguet_has_option_id 1 ;;
        1) _moguet_has_option_id 0 ;;
        2) _moguet_has_option_id 3 ;;
        3) _moguet_has_option_id 2 ;;
        6) _moguet_has_option_id 7 || _moguet_has_option_id 8 ;;
        7) _moguet_has_option_id 6 || _moguet_has_option_id 8 ;;
        8) _moguet_has_option_id 6 || _moguet_has_option_id 7 ;;
        9) _moguet_has_option_id 10 ;;
        10) _moguet_has_option_id 9 ;;
        11) _moguet_has_option_id 12 ;;
        12) _moguet_has_option_id 11 ;;
        *) return 1 ;;
    esac
}

_moguet() {
    local cur operation candidate option_id
    local -a candidates filtered
    cur="${COMP_WORDS[COMP_CWORD]}"
    operation="$(_moguet_find_operation || true)"

    if [[ -z $operation ]]; then
        candidates=(build upgrade upgrade-aur upgrade-all clean deps plan fetch add-src edit-src list-src del-src revert -G -Gp -S -Syu -Su -Ss -Si -Qua -h --help -V --version --edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --rmdeps --select --aur --repo --details)
    else
        case "$operation" in
        build)
            if _moguet_has_option_id 15; then
                if _moguet_form_prefix_valid build 1; then
                    candidates=(--edit --noedit --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --local)
                else
                    candidates=()
                fi
            elif _moguet_has_operand build; then
                if _moguet_form_prefix_valid build 0; then
                    candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild)
                else
                    candidates=()
                fi
            else
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --local)
            fi
            ;;
        upgrade)
            if _moguet_form_prefix_valid upgrade 0; then
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild)
            else
                candidates=()
            fi
            ;;
        upgrade-aur)
            if _moguet_form_prefix_valid upgrade-aur 0; then
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild)
            else
                candidates=()
            fi
            ;;
        upgrade-all)
            if _moguet_form_prefix_valid upgrade-all 0; then
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild)
            else
                candidates=()
            fi
            ;;
        clean)
            if _moguet_form_prefix_valid clean 0; then
                candidates=(--noconfirm)
            else
                candidates=()
            fi
            ;;
        deps)
            if _moguet_form_prefix_valid deps 0; then
                candidates=(--noconfirm --details --recursive)
            else
                candidates=()
            fi
            ;;
        plan)
            if _moguet_form_prefix_valid plan 0; then
                candidates=(--noconfirm --details)
            else
                candidates=()
            fi
            ;;
        fetch)
            if _moguet_form_prefix_valid fetch 0; then
                candidates=(--noconfirm --dry-run)
            else
                candidates=()
            fi
            ;;
        add-src)
            if _moguet_form_prefix_valid add-src 0; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        edit-src)
            if _moguet_form_prefix_valid edit-src 0; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        list-src)
            if _moguet_form_prefix_valid list-src 0; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        del-src)
            if _moguet_form_prefix_valid del-src 0; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        revert)
            if _moguet_form_prefix_valid revert 0; then
                candidates=(--noconfirm)
            else
                candidates=()
            fi
            ;;
        -G)
            if _moguet_form_prefix_valid -G 0; then
                candidates=(--output-dir=)
            else
                candidates=()
            fi
            ;;
        -Gp)
            if _moguet_form_prefix_valid -Gp 0; then
                candidates=()
            else
                candidates=()
            fi
            ;;
        -S)
            if _moguet_has_option_id 10; then
                if _moguet_form_prefix_valid -S 0; then
                    candidates=(--select --needed --edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --aur --repo --details)
                else
                    candidates=()
                fi
            else
                candidates=(--needed --noconfirm --select)
            fi
            ;;
        -Syu)
            if _moguet_has_option_id 12; then
                if _moguet_form_prefix_valid -Syu 1; then
                    candidates=(--repo --needed --noconfirm --dry-run)
                else
                    candidates=()
                fi
            elif _moguet_has_operand -Syu; then
                candidates=(--needed --noconfirm)
            else
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --needed --repo)
            fi
            ;;
        -Su)
            if _moguet_has_option_id 12; then
                if _moguet_form_prefix_valid -Su 1; then
                    candidates=(--repo --needed --noconfirm --dry-run)
                else
                    candidates=()
                fi
            elif _moguet_has_operand -Su; then
                candidates=(--needed --noconfirm)
            else
                candidates=(--edit --noedit --diff --nodiff --noconfirm --dry-run --build-mode= --rebuild --cleanbuild --needed --repo)
            fi
            ;;
        -Ss) candidates=(--needed --noconfirm) ;;
        -Si) candidates=(--needed --noconfirm) ;;
        -Qua) candidates=(--needed --noconfirm) ;;
        -h) candidates=() ;;
        --help) candidates=() ;;
        -V) candidates=() ;;
        --version) candidates=() ;;
        __delegated__) candidates=(--needed --noconfirm) ;;
        *) candidates=() ;;
        esac
    fi

    filtered=()
    for candidate in "${candidates[@]}"; do
        option_id="$(_moguet_option_id "$candidate" || true)"
        if [[ -n $option_id ]]; then
            case "$option_id" in
            13|14|15|16)
                _moguet_has_option_id "$option_id" && continue
                ;;
            esac
            _moguet_conflicts_with_present_option "$option_id" && continue
        fi
        filtered+=("$candidate")
    done

    COMPREPLY=()
    COMPREPLY=( $(compgen -W "${filtered[*]}" -- "$cur" || true) )
}

complete -F _moguet moguet
