# Generated by scripts/generate_completions.py; do not edit.
# Description locale: en
# Canonical closed grammar (projected from source/cli_authority.hpp):
#   build <pkg> [V=K...]
#   build --local <directory> [V=K...]
#   upgrade
#   upgrade-aur
#   upgrade-all
#   clean
#   deps [--recursive] <pkg>...
#   plan <pkg>...
#   fetch <pkg>...
#   add-src <item>...
#   edit-src <pkg>...
#   list-src
#   del-src <pkg>...
#   revert <pkg>...
#   -G <pkg> [--output-dir=DIR]
#   -Gp <pkg>
#   -S --select [--needed] <query>
#   -Syu [--needed]
#   -Syu --repo [--needed]
#   -Su [--needed]
#   -Su --repo [--needed]

function __moguet_option_id --argument-names word
    switch $word
        case '-h' '--help'
            echo 13
            return 0
        case '-V' '--version'
            echo 14
            return 0
        case '--edit'
            echo 0
            return 0
        case '--noedit'
            echo 1
            return 0
        case '--diff'
            echo 2
            return 0
        case '--nodiff'
            echo 3
            return 0
        case '--noconfirm'
            echo 4
            return 0
        case '--dry-run'
            echo 5
            return 0
        case '--build-mode' '--build-mode=*'
            echo 6
            return 0
        case '--rebuild'
            echo 7
            return 0
        case '--cleanbuild'
            echo 8
            return 0
        case '--rmdeps'
            echo 9
            return 0
        case '--select'
            echo 10
            return 0
        case '--aur'
            echo 11
            return 0
        case '--repo'
            echo 12
            return 0
        case '--details'
            echo 20
            return 0
        case '--local'
            echo 15
            return 0
        case '--output-dir' '--output-dir=*'
            echo 16
            return 0
        case '--recursive'
            echo 17
            return 0
        case '--needed'
            echo 18
            return 0
    end
    return 1
end

function __moguet_has_option_id --argument-names expected
    for word in (commandline -opc)[2..-1]
        set -l actual (__moguet_option_id $word)
        test "$actual" = "$expected"; and return 0
    end
    return 1
end

function __moguet_operation
    for word in (commandline -opc)[2..-1]
        switch $word
        case '-h' '--help' '-V' '--version' 'build' 'upgrade' 'upgrade-aur' 'upgrade-all' 'clean' 'deps' 'plan' 'fetch' 'add-src' 'edit-src' 'list-src' 'del-src' 'revert' '-G' '-Gp' '-S' '-Syu' '-Su' '-Ss' '-Si' '-Qua'
            echo $word
            return 0
        end
        __moguet_option_id $word >/dev/null; and continue
        string match -q -- '-*' $word; and echo __delegated__; and return 0
        echo __invalid__
        return 0
    end
    return 1
end

function __moguet_has_operand --argument-names expected_operation
    set -l seen_operation false
    for word in (commandline -opc)[2..-1]
        if test $seen_operation = false
            test "$word" = "$expected_operation"; and set seen_operation true
            continue
        end
        __moguet_option_id $word >/dev/null; or return 0
    end
    return 1
end

function __moguet_is_assignment_operand --argument-names word
    string match -q -- '*=*' "$word"
end

function __moguet_form_prefix_valid --argument-names expected_operation form_index
    set -l seen_operation false
    set -l operands
    for word in (commandline -opc)[2..-1]
        if test $seen_operation = false
            test "$word" = "$expected_operation"; and set seen_operation true
            continue
        end
        __moguet_option_id $word >/dev/null; and continue
        set -a operands "$word"
    end
    switch "$expected_operation:$form_index"
        case 'build:0'
            test (count $operands) -eq 0; and return 0
            __moguet_is_assignment_operand "$operands[1]"; and return 1
            for word in $operands[2..-1]
                __moguet_is_assignment_operand "$word"; or return 1
            end
            return 0
        case 'build:1'
            test (count $operands) -eq 0; and return 0
            __moguet_is_assignment_operand "$operands[1]"; and return 1
            for word in $operands[2..-1]
                __moguet_is_assignment_operand "$word"; or return 1
            end
            return 0
        case 'upgrade:0'
            test (count $operands) -le 0; and return 0
            return 1
        case 'upgrade-aur:0'
            test (count $operands) -le 0; and return 0
            return 1
        case 'upgrade-all:0'
            test (count $operands) -le 0; and return 0
            return 1
        case 'clean:0'
            test (count $operands) -le 0; and return 0
            return 1
        case 'deps:0'
            return 0
        case 'plan:0'
            return 0
        case 'fetch:0'
            return 0
        case 'add-src:0'
            test (count $operands) -eq 0; and return 0
            __moguet_is_assignment_operand "$operands[1]"; and return 1
            return 0
        case 'edit-src:0'
            return 0
        case 'list-src:0'
            test (count $operands) -le 0; and return 0
            return 1
        case 'del-src:0'
            return 0
        case 'revert:0'
            return 0
        case '-G:0'
            test (count $operands) -le 1; and return 0
            return 1
        case '-Gp:0'
            test (count $operands) -le 1; and return 0
            return 1
        case '-S:0'
            test (count $operands) -le 1; and return 0
            return 1
        case '-Syu:0'
            test (count $operands) -le 0; and return 0
            return 1
        case '-Syu:1'
            test (count $operands) -le 0; and return 0
            return 1
        case '-Su:0'
            test (count $operands) -le 0; and return 0
            return 1
        case '-Su:1'
            test (count $operands) -le 0; and return 0
            return 1
    end
    return 1
end

function __moguet_operation_allows --argument-names option_id
    set -l operation (__moguet_operation)
    if test -z "$operation"
        contains -- $option_id 13 14 0 1 2 3 4 5 6 7 8 9 10 11 12 20; and return 0; or return 1
    end
    switch $operation
        case 'build'
            set -l selected false
            __moguet_has_option_id 15; and set selected true
            if test $selected = true
                __moguet_form_prefix_valid 'build' 1; or return 1
                contains -- $option_id 0 1 4 5 6 7 8 15; and return 0; or return 1
            else if __moguet_has_operand 'build'
                __moguet_form_prefix_valid 'build' 0; or return 1
                contains -- $option_id 0 1 2 3 4 5 6 7 8 20; and return 0; or return 1
            else
                contains -- $option_id 0 1 2 3 4 5 6 7 8 20 15; and return 0; or return 1
            end
        case 'upgrade'
            __moguet_form_prefix_valid 'upgrade' 0; or return 1
            contains -- $option_id 0 1 2 3 4 5 6 7 8; and return 0; or return 1
        case 'upgrade-aur'
            __moguet_form_prefix_valid 'upgrade-aur' 0; or return 1
            contains -- $option_id 0 1 2 3 4 5 6 7 8; and return 0; or return 1
        case 'upgrade-all'
            __moguet_form_prefix_valid 'upgrade-all' 0; or return 1
            contains -- $option_id 0 1 2 3 4 5 6 7 8; and return 0; or return 1
        case 'clean'
            __moguet_form_prefix_valid 'clean' 0; or return 1
            contains -- $option_id 4; and return 0; or return 1
        case 'deps'
            __moguet_form_prefix_valid 'deps' 0; or return 1
            contains -- $option_id 4 20 17; and return 0; or return 1
        case 'plan'
            __moguet_form_prefix_valid 'plan' 0; or return 1
            contains -- $option_id 4 20; and return 0; or return 1
        case 'fetch'
            __moguet_form_prefix_valid 'fetch' 0; or return 1
            contains -- $option_id 4 5; and return 0; or return 1
        case 'add-src'
            __moguet_form_prefix_valid 'add-src' 0; or return 1
            return 1
        case 'edit-src'
            __moguet_form_prefix_valid 'edit-src' 0; or return 1
            return 1
        case 'list-src'
            __moguet_form_prefix_valid 'list-src' 0; or return 1
            return 1
        case 'del-src'
            __moguet_form_prefix_valid 'del-src' 0; or return 1
            return 1
        case 'revert'
            __moguet_form_prefix_valid 'revert' 0; or return 1
            contains -- $option_id 4; and return 0; or return 1
        case '-G'
            __moguet_form_prefix_valid '-G' 0; or return 1
            contains -- $option_id 16; and return 0; or return 1
        case '-Gp'
            __moguet_form_prefix_valid '-Gp' 0; or return 1
            return 1
        case '-S'
            set -l selected false
            __moguet_has_option_id 10; and set selected true
            if test $selected = true
                __moguet_form_prefix_valid '-S' 0; or return 1
                contains -- $option_id 10 18 0 1 2 3 4 5 6 7 8 11 12 20; and return 0; or return 1
            else
                contains -- $option_id 18 4 10; and return 0; or return 1
            end
        case '-Syu'
            set -l selected false
            __moguet_has_option_id 12; and set selected true
            if test $selected = true
                __moguet_form_prefix_valid '-Syu' 1; or return 1
                contains -- $option_id 12 18 4 5 19; and return 0; or return 1
            else if __moguet_has_operand '-Syu'
                contains -- $option_id 18 4; and return 0; or return 1
            else
                contains -- $option_id 0 1 2 3 4 5 6 7 8 18 12 19; and return 0; or return 1
            end
        case '-Su'
            set -l selected false
            __moguet_has_option_id 12; and set selected true
            if test $selected = true
                __moguet_form_prefix_valid '-Su' 1; or return 1
                contains -- $option_id 12 18 4 5 19; and return 0; or return 1
            else if __moguet_has_operand '-Su'
                contains -- $option_id 18 4; and return 0; or return 1
            else
                contains -- $option_id 0 1 2 3 4 5 6 7 8 18 12 19; and return 0; or return 1
            end
        case '-Ss'
            contains -- $option_id 18 4; and return 0; or return 1
        case '-Si'
            contains -- $option_id 18 4; and return 0; or return 1
        case '-Qua'
            contains -- $option_id 18 4; and return 0; or return 1
        case __delegated__
            contains -- $option_id 18 4; and return 0; or return 1
    end
    return 1
end

function __moguet_candidate_available --argument-names option_id
    __moguet_operation_allows $option_id; or return 1
    contains -- $option_id 13 14 15 16; and __moguet_has_option_id $option_id; and return 1
    switch $option_id
        case 0
            __moguet_has_option_id 1; and return 1
        case 1
            __moguet_has_option_id 0; and return 1
        case 2
            __moguet_has_option_id 3; and return 1
        case 3
            __moguet_has_option_id 2; and return 1
        case 6
            __moguet_has_option_id 7; and return 1
            __moguet_has_option_id 8; and return 1
        case 7
            __moguet_has_option_id 6; and return 1
            __moguet_has_option_id 8; and return 1
        case 8
            __moguet_has_option_id 6; and return 1
            __moguet_has_option_id 7; and return 1
        case 9
            __moguet_has_option_id 10; and return 1
        case 10
            __moguet_has_option_id 9; and return 1
        case 11
            __moguet_has_option_id 12; and return 1
        case 12
            __moguet_has_option_id 11; and return 1
    end
    return 0
end

function __moguet_no_operation
    not __moguet_operation >/dev/null
end

complete -c moguet -f -n '__moguet_no_operation' -a 'build' -d 'Build one remote package or local PKGBUILD root without saving a preference'
complete -c moguet -f -n '__moguet_no_operation' -a 'upgrade' -d 'Run the source-aware system update and apply saved source-build preferences'
complete -c moguet -f -n '__moguet_no_operation' -a 'upgrade-aur' -d 'Update only installed AUR packages while applying saved source-build preferences'
complete -c moguet -f -n '__moguet_no_operation' -a 'upgrade-all' -d 'Run the full source-aware repository, configured-source, and remaining-AUR update'
complete -c moguet -f -n '__moguet_no_operation' -a 'clean' -d 'Clean package and build caches'
complete -c moguet -f -n '__moguet_no_operation' -a 'deps' -d 'Classify AUR dependencies for one or more packages'
complete -c moguet -f -n '__moguet_no_operation' -a 'plan' -d 'Show the AUR build-order plan for one or more packages'
complete -c moguet -f -n '__moguet_no_operation' -a 'fetch' -d 'Fetch AUR build repositories without updating working trees'
complete -c moguet -f -n '__moguet_no_operation' -a 'add-src' -d 'Enable source-build preferences for one or more items'
complete -c moguet -f -n '__moguet_no_operation' -a 'edit-src' -d 'Edit one or more source-build preferences'
complete -c moguet -f -n '__moguet_no_operation' -a 'list-src' -d 'List source-build preferences'
complete -c moguet -f -n '__moguet_no_operation' -a 'del-src' -d 'Remove one or more source-build preferences'
complete -c moguet -f -n '__moguet_no_operation' -a 'revert' -d 'Remove preferences and reinstall binary packages'
complete -c moguet -f -n '__moguet_no_operation' -a '-G' -d 'Export one AUR PackageBase repository without building or installing'
complete -c moguet -f -n '__moguet_no_operation' -a '-Gp' -d 'Print one AUR PackageBase PKGBUILD without keeping a checkout'
complete -c moguet -f -n '__moguet_no_operation' -a '-S' -d 'Install packages'
complete -c moguet -f -n '__moguet_no_operation' -a '-Syu' -d 'Update repository packages and normal installed AUR packages without saved source-build preferences'
complete -c moguet -f -n '__moguet_no_operation' -a '-Su' -d 'Update repository packages and normal installed AUR packages without refreshing sync databases or using saved source-build preferences'
complete -c moguet -f -n '__moguet_no_operation' -a '-Ss' -d 'Search for packages'
complete -c moguet -f -n '__moguet_no_operation' -a '-Si' -d 'Show package information'
complete -c moguet -f -n '__moguet_no_operation' -a '-Qua' -d 'Check AUR and foreign-package updates'
complete -c moguet -f -n '__moguet_candidate_available 13' -a '-h' -d 'Show the help message and exit'
complete -c moguet -f -n '__moguet_candidate_available 13' -a '--help' -d 'Show the help message and exit'
complete -c moguet -f -n '__moguet_candidate_available 14' -a '-V' -d 'Show version information and exit'
complete -c moguet -f -n '__moguet_candidate_available 14' -a '--version' -d 'Show version information and exit'
complete -c moguet -f -n '__moguet_candidate_available 0' -a '--edit' -d 'Open or edit PKGBUILD and .install files for this invocation'
complete -c moguet -f -n '__moguet_candidate_available 1' -a '--noedit' -d 'Skip invocation-local PKGBUILD and .install editing'
complete -c moguet -f -n '__moguet_candidate_available 2' -a '--diff' -d 'Review repository updates; for AUR, review the exact target from the previous reviewed revision or all tracked source initially'
complete -c moguet -f -n '__moguet_candidate_available 3' -a '--nodiff' -d 'Skip repository diff / reviewed-source review without advancing reviewed state'
complete -c moguet -f -n '__moguet_candidate_available 4' -a '--noconfirm' -d 'Skip prompts on supported routes; forwarding remains route-owned'
complete -c moguet -f -n '__moguet_candidate_available 5' -a '--dry-run' -d 'Observe a supported mutating operation without changing persistent state'
complete -c moguet -f -n '__moguet_candidate_available 6' -a '--build-mode=' -d 'Select the source-build mode'
complete -c moguet -f -n '__moguet_candidate_available 7' -a '--rebuild' -d 'Compatibility alias for --build-mode=rebuild'
complete -c moguet -f -n '__moguet_candidate_available 8' -a '--cleanbuild' -d 'Compatibility alias for --build-mode=clean'
complete -c moguet -f -n '__moguet_candidate_available 9' -a '--rmdeps' -d 'Preview newly installed build dependencies after remote AUR build success; remove only with explicit approval'
complete -c moguet -f -n '__moguet_candidate_available 10' -a '--select' -d 'Interactively select source-aware package candidates for plain -S'
complete -c moguet -f -n '__moguet_candidate_available 11' -a '--aur' -d 'Limit supported sync operations to AUR'
complete -c moguet -f -n '__moguet_candidate_available 12' -a '--repo' -d 'Use only official binary repositories; with -Syu / -Su, run the repository system upgrade only'
complete -c moguet -f -n '__moguet_candidate_available 20' -a '--details' -d 'Show detailed diagnostic and provenance information for remote build, plan, deps, and -S --select; presentation only'
complete -c moguet -f -n '__moguet_candidate_available 15' -a '--local' -d 'Use one local PKGBUILD directory as the build root'
complete -c moguet -f -n '__moguet_candidate_available 16' -a '--output-dir=' -d 'Select an existing export parent for -G'
complete -c moguet -f -n '__moguet_candidate_available 17' -a '--recursive' -d 'Resolve dependencies recursively'
complete -c moguet -f -n '__moguet_candidate_available 18' -a '--needed' -d 'Preserve pacman --needed semantics at the installation phase owned by the selected route'
