# Only the new whole-owner consumer boundary; 4B1 construction probes stay
# in their own lane. Compiler/profile inputs are shared with the canonical gate.
get_filename_component(_s4_dir "${MOGUET_NEGATIVE_COMPILE_PROJECT_OPTIONS_FILE}" DIRECTORY)
set(_s4_probe "${_s4_dir}/pinned-s4.cpp")
foreach(_case IN ITEMS baseline borrowed_owner foreign_context private_selection inverse_consumer)
    set(_include "#include \"pinned_submodule_workspace.hpp\"\n")
    set(_expected "private|deleted|no matching function")
    if(_case STREQUAL "baseline")
        set(_body "void consume(SourceReadyPinnedSubmoduleWorkspace source) { auto result = resume_evaluated_devel_source(std::move(source)); }\n")
    elseif(_case STREQUAL "borrowed_owner")
        set(_body "void forge(SourceReadyPinnedSubmoduleWorkspace& source) { auto result = resume_evaluated_devel_source(source); }\n")
    elseif(_case STREQUAL "foreign_context")
        set(_body "void forge(SourceReadyPinnedSubmoduleWorkspace source, InvocationOwnedSourceBuildContext other) { auto result = resume_evaluated_devel_source(std::move(source), std::move(other)); }\n")
    elseif(_case STREQUAL "private_selection")
        set(_body "void forge(SourceReadyPinnedSubmoduleWorkspace source) { auto& selection = PinnedSubmoduleWorkspaceAuthority::selection(source); }\n")
    else()
        set(_include "#include \"pinned_submodule_workspace_authority.hpp\"\n")
        set(_expected "redefinition")
        set(_body "class EvaluatedDevelSourceBuildAuthority { public: static EvaluatedDevelSourceSelection& forge(SourceReadyPinnedSubmoduleWorkspace& source) { return PinnedSubmoduleWorkspaceAuthority::selection(source); } };\n")
    endif()
    file(WRITE "${_s4_probe}" "${_include}${_body}")
    execute_process(COMMAND ${_moguet_compile_command} ${_moguet_common_arguments} -fsyntax-only "${_s4_probe}"
        RESULT_VARIABLE _status OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    file(WRITE "${_s4_dir}/pinned-s4-${_case}.diagnostic.txt" "${_stdout}${_stderr}")
    if(_case STREQUAL "baseline")
        if(NOT "${_status}" STREQUAL "0")
            message(FATAL_ERROR "4B2 consumer baseline failed: ${_stderr}")
        endif()
    elseif("${_status}" STREQUAL "0" OR NOT "${_stderr}" MATCHES "${_expected}")
        message(FATAL_ERROR "4B2 ${_case} failed expected rejection: ${_status}: ${_stderr}")
    endif()
endforeach()
message(STATUS "4B2 consumer baseline + 4 negative diagnostics PASS")
