# Reuse the effective compiler/profile; this lane has no runtime authority.
get_filename_component(_workspace_dir "${MOGUET_NEGATIVE_COMPILE_PROJECT_OPTIONS_FILE}" DIRECTORY)
set(_workspace_probe "${_workspace_dir}/pinned-workspace.cpp")
foreach(_case IN ITEMS baseline default_constructor copy private_constructor opaque_backing raw_path raw_metadata unaccepted decoded_provenance completed_proof inverse_friend)
    set(_include "#include \"pinned_submodule_workspace.hpp\"\n#include <type_traits>\n")
    set(_expected "private|deleted|no matching function|no viable conversion|could not convert|cannot convert")
    if(_case STREQUAL "baseline")
        set(_body "static_assert(!std::is_default_constructible_v<SourceReadyPinnedSubmoduleWorkspace>);\nstatic_assert(!std::is_copy_constructible_v<SourceReadyPinnedSubmoduleWorkspace>);\nstatic_assert(std::is_nothrow_move_constructible_v<SourceReadyPinnedSubmoduleWorkspace>);\nstatic_assert(std::is_invocable_v<decltype(materialize_pinned_submodule_workspace), AcceptedPinnedSubmoduleClosure>);\n")
    elseif(_case STREQUAL "default_constructor")
        set(_body "void forge() { SourceReadyPinnedSubmoduleWorkspace value; }\n")
    elseif(_case STREQUAL "copy")
        set(_body "void forge(const SourceReadyPinnedSubmoduleWorkspace& source) { auto value = source; }\n")
    elseif(_case STREQUAL "private_constructor")
        set(_body "void forge() { SourceReadyPinnedSubmoduleWorkspace value(nullptr); }\n")
    elseif(_case STREQUAL "opaque_backing")
        set(_body "struct PinnedSubmoduleWorkspaceData { static SourceReadyPinnedSubmoduleWorkspace forge() { return SourceReadyPinnedSubmoduleWorkspace(nullptr); } };\n")
    elseif(_case STREQUAL "inverse_friend")
        set(_include "#include \"pinned_submodule_workspace_authority.hpp\"\n")
        set(_expected "redefinition")
        set(_body "class SourceReadyPinnedSubmoduleWorkspace { public: static auto forge() { return &PinnedSubmoduleWorkspaceAuthority::clone_objects; } };\n")
    elseif(_case STREQUAL "raw_metadata")
        set(_body "void forge(std::string root, std::vector<PinnedSubmoduleNode> nodes, std::vector<PinnedSubmoduleEdge> edges) { SourceReadyPinnedSubmoduleWorkspace value(root, nodes, edges, true); }\n")
    else()
        if(_case STREQUAL "raw_path")
            set(_input "std::filesystem::path")
        elseif(_case STREQUAL "unaccepted")
            set(_input "InvocationOwnedPinnedSubmoduleClosure")
        elseif(_case STREQUAL "decoded_provenance")
            set(_input "DevelBuildProvenance")
        else()
            set(_input "EvaluatedDevelSourceBuildProof")
        endif()
        set(_body "void forge(${_input} input) { auto value = materialize_pinned_submodule_workspace(std::move(input)); }\n")
    endif()
    file(WRITE "${_workspace_probe}" "${_include}${_body}")
    execute_process(COMMAND ${_moguet_compile_command} ${_moguet_common_arguments} -fsyntax-only "${_workspace_probe}"
        RESULT_VARIABLE _status OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    file(WRITE "${_workspace_dir}/pinned-workspace-${_case}.diagnostic.txt" "${_stdout}${_stderr}")
    if(_case STREQUAL "baseline")
        if(NOT "${_status}" STREQUAL "0")
            message(FATAL_ERROR "4B1 baseline failed: ${_stderr}")
        endif()
    elseif("${_status}" STREQUAL "0" OR NOT "${_stderr}" MATCHES "${_expected}")
        message(FATAL_ERROR "4B1 ${_case} failed expected rejection: ${_status}: ${_stderr}")
    endif()
endforeach()
message(STATUS "4B1 workspace authority baseline + 10 negative diagnostics PASS")
