# Uses the verified compiler/profile inputs from MoguetNegativeCompile.cmake.
get_filename_component(_moguet_review_probe_dir "${MOGUET_NEGATIVE_COMPILE_PROJECT_OPTIONS_FILE}" DIRECTORY)
set(_moguet_review_probe "${_moguet_review_probe_dir}/pinned-closure-review.cpp")
set(_moguet_review_include "#include \"pinned_submodule_closure_review.hpp\"\n#include <type_traits>\n")
foreach(_moguet_review_case IN ITEMS baseline default_constructor copy private_constructor raw_metadata confirmation_token decoded_provenance completed_proof raw_input)
    set(_moguet_review_expected "is private within this context|private member|private constructor|deleted|no matching function|no viable conversion|could not convert|cannot convert")
    if(_moguet_review_case STREQUAL "baseline")
        set(_moguet_review_body "static_assert(!std::is_default_constructible_v<AcceptedPinnedSubmoduleClosure>);\nstatic_assert(!std::is_copy_constructible_v<AcceptedPinnedSubmoduleClosure>);\nstatic_assert(std::is_nothrow_move_constructible_v<AcceptedPinnedSubmoduleClosure>);\nstatic_assert(!std::is_constructible_v<AcceptedPinnedSubmoduleClosure, bool>);\n")
    elseif(_moguet_review_case STREQUAL "default_constructor")
        set(_moguet_review_body "void forge() { AcceptedPinnedSubmoduleClosure value; }\n")
    elseif(_moguet_review_case STREQUAL "copy")
        set(_moguet_review_body "void forge(const AcceptedPinnedSubmoduleClosure& source) { auto value = source; }\n")
    elseif(_moguet_review_case STREQUAL "private_constructor")
        set(_moguet_review_body "void forge(InvocationOwnedPinnedSubmoduleClosure closure, ExplicitConfirmationAcceptance token) { AcceptedPinnedSubmoduleClosure value(std::move(closure), std::move(token)); }\n")
    elseif(_moguet_review_case STREQUAL "raw_metadata")
        set(_moguet_review_body "void forge(std::vector<PinnedSubmoduleNode> nodes, std::vector<PinnedSubmoduleEdge> edges) { AcceptedPinnedSubmoduleClosure value(std::move(nodes), std::move(edges), true); }\n")
    elseif(_moguet_review_case STREQUAL "confirmation_token")
        set(_moguet_review_body "void forge(InvocationOwnedPinnedSubmoduleClosure closure, ExplicitConfirmationAcceptance token) { auto value = review_pinned_submodule_closure(std::move(closure), std::move(token)); }\n")
    elseif(_moguet_review_case STREQUAL "raw_input")
        set(_moguet_review_body "void forge(std::vector<PinnedSubmoduleNode> nodes) { auto value = review_pinned_submodule_closure(std::move(nodes)); }\n")
    else()
        if(_moguet_review_case STREQUAL "decoded_provenance")
            set(_moguet_review_input "DevelBuildProvenance")
        else()
            set(_moguet_review_input "EvaluatedDevelSourceBuildProof")
        endif()
        set(_moguet_review_body "void forge(${_moguet_review_input} source) { AcceptedPinnedSubmoduleClosure value(std::move(source)); }\n")
    endif()
    file(WRITE "${_moguet_review_probe}" "${_moguet_review_include}${_moguet_review_body}")
    execute_process(COMMAND ${_moguet_compile_command} ${_moguet_common_arguments} -fsyntax-only "${_moguet_review_probe}"
        RESULT_VARIABLE _moguet_review_status OUTPUT_VARIABLE _moguet_review_stdout ERROR_VARIABLE _moguet_review_stderr)
    if(_moguet_review_case STREQUAL "baseline")
        if(NOT "${_moguet_review_status}" STREQUAL "0")
            message(FATAL_ERROR "4B0 baseline failed: ${_moguet_review_stderr}")
        endif()
    elseif("${_moguet_review_status}" STREQUAL "0" OR NOT "${_moguet_review_stderr}" MATCHES "${_moguet_review_expected}")
        message(FATAL_ERROR "4B0 ${_moguet_review_case} failed expected rejection: ${_moguet_review_status}: ${_moguet_review_stderr}")
    endif()
    file(WRITE "${_moguet_review_probe_dir}/pinned-closure-review-${_moguet_review_case}.diagnostic.txt" "${_moguet_review_stdout}${_moguet_review_stderr}")
endforeach()
message(STATUS "4B0 review authority baseline + 8 negative diagnostics PASS")
